sudo: required
services:
  - docker

before_install:
  - docker build -t icerig/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true icerig/react-test npm test

after_success:
  - docker build -t icerig/multi-client ./client
  - docker build -t icerig/multi-nginx ./nginx
  - docker build -t icerig/multi-server ./server
  - docker build -t icerig/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to Docker hub
  - docker push icerig/multi-client
  - docker push icerig/multi-nginx
  - docker push icerig/multi-server
  - docker push icerig/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker2'
  env: 'MultiDocker2-env'
  bucket_name: 'elasticbeanstalk-us-east-1-163755040348'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY